### ISSUE TITLE
outdated newtonsoft.json

### ISSUE THREAD

**Issue by Amialc** [auth0/Xamarin.Auth0Client#20]
Samples using outdated version of `Newtonsoft.Json`. ([Android](https://github.com/auth0/Xamarin.Auth0Client/blob/master/samples/Auth0Client.Android.Sample/packages.config#L3), [iOS](https://github.com/auth0/Xamarin.Auth0Client/blob/master/samples/Auth0Client.iOS.Sample/packages.config))

**Comment by Architekt909** [comment]
The component is using a 6.x version of Newtonsoft.Json. The current version is up to 9.x. This causes errors when you add the component to your project but you already have the 9.x version of Newtonsoft.Json added as a NuGet package (since many other NuGet packages also rely on this library). Maybe this could be fixed by making the Auth0 component a NuGet package. Either way, it's pretty poor for the component to be generating errors when you try to add it due to an out of date/conflicting dependency.
